
{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}
{% set name = "xrd_simulator" %}
{% set version = data.get('version') %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fe95366e9f94c6a9f43d4e5fcde0b578c28ed41d9c3369cb51097260a4d45150

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --force-reinstall -vv "

requirements:
  host:
    - pip
    - python
  run:
    - python
    - matplotlib==3.3.1
    - numpy==1.21.4
    - meshio==5.0.2
    - pygalmesh==0.10.6
    - scipy==1.6.1
    - numba==0.53.0
    - pycifrw==4.4.3
    - conda-forge::conda_build_test_requirement

test:
  imports:
    - xrd_simulator

about:
  home: https://github.com/AxelHenningsson/xrd_simulator
  license: MIT
  license_family: MIT
  summary: {{ data.get('description') }}
  description: |
    A package for simulating X-ray Diffraction from polycrystals. Note that the conda-forge channel
    must be on your default channels for installation.