
{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}
{% set name = "xrd_simulator" %}
{% set version = data.get('version') %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://files.pythonhosted.org/packages/4c/4f/1362dcac39a4f7c99513650dd929be047b67ee2b7f5c161894efa455950a/xrd_simulator-0.1.3.tar.gz
  sha256: ba090164a05faed1125bc5e19133415d2dc66ac8b3a9b10e98ade735cf4c6a0a

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --force-reinstall -vv "

requirements:
  host:
    - pip
    - python
  run:
    - python
    - matplotlib==3.3.1
    - numpy==1.21.4
    - meshio==5.0.2
    - pygalmesh==0.10.6
    - scipy==1.6.1
    - numba==0.53.0
    - pycifrw==4.4.3

test:
  imports:
    - xrd_simulator

about:
  home: https://github.com/AxelHenningsson/xrd_simulator
  license: MIT
  license_family: MIT
  summary: {{ data.get('description') }}
  description: |
    A package for simulating X-ray Diffraction from polycrystals. Note that the conda-forge channel
    must be on your default channels for installation. Alternatively, use:
    conda install -c conda-forge -c axiomel xrd_simulator