
{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}
{% set name = "xrd_simulator" %}
{% set version = data.get('version') %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://files.pythonhosted.org/packages/1e/b2/22d27dcada96677a8eb71aee5f23dadb2c31ca682a84890a9ef9e02e370e/xrd_simulator-0.1.2.tar.gz
  sha256: a87eb5da72403b2ccdcc298d33c014e2cbe223d3c8b9c37b335fec117f867117

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --force-reinstall -vv "

requirements:
  host:
    - pip
    - python
  run:
    - python
    - matplotlib==3.5.1
    - numpy==1.21.4
    - meshio==5.0.2
    - pygalmesh==0.10.6
    - scipy==1.7.3
    - numba==0.54.1
    - pycifrw==4.4.3

test:
  imports:
    - xrd_simulator

about:
  home: https://github.com/AxelHenningsson/xrd_simulator
  license: MIT
  license_family: MIT
  summary: {{ data.get('description') }}
  description: |
    A package for simulating X-ray Diffraction from polycrystals. Note that the conda-forge channel
    must be on your default channels for installation. Alternatively, use:
    conda install -c conda-forge -c axiomel xrd_simulator