
{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}
{% set name = "xrd_simulator" %}
{% set version = data.get('version') %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://files.pythonhosted.org/packages/e0/3e/334abb115860dc63469bddf23b6a7321f04600947b6adc8fcefdccef69d8/xrd_simulator-0.0.8.tar.gz
  sha256: 65b8b8fe8fbbb484feab14996d35a5ef5dfc17dfc41c72d014ad683c0964a7eb

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --force-reinstall -vv "

requirements:
  host:
    - pip
    - python
  run:
    - python
    - matplotlib==3.3.1
    - numpy==1.21.4
    - meshio==5.0.2
    - pygalmesh==0.10.6
    - scipy==1.6.1
    - numba==0.53.0
    - pycifrw==4.4.3

test:
  imports:
    - xrd_simulator

about:
  home: https://github.com/AxelHenningsson/xrd_simulator
  license: MIT
  license_family: MIT
  summary: {{ data.get('description') }}