
{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}
{% set name = "xrd_simulator" %}
{% set version = data.get('version') %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 60088a18c6b3c1dec29aa03274914a766012c9e76b501b6848fc37abac28be81

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8,<3.9
  run:
    - matplotlib-base
    - meshio ==5.0.2
    - numba ==0.53.0
    - numpy ==1.21.4
    - pycifrw ==4.4.3
    - pygalmesh ==0.10.6
    - python >=3.8,<3.9
    - scipy ==1.6.1

test:
  imports:
    - tests
    - xrd_simulator
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fable-3dxrd/xrd_simulator
  doc_url: https://fable-3dxrd.github.io/xrd_simulator
  dev_url: https://github.com/fable-3dxrd/xrd_simulator
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: {{ data.get('description') }}
  description: |
    A package for simulating X-ray Diffraction from polycrystals. Note that the conda-forge channel
    must be on your channels for installation.